<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.ruoyi</groupId>
        <artifactId>ruoyi-modules</artifactId>
        <version>3.6.7</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>ruoyi-modules-zlm</artifactId>

    <description>
        ruoyi-modules-zlm zlm模块
    </description>

    <dependencies>

        <!-- SpringCloud Alibaba Nacos -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <!-- SpringCloud Alibaba Nacos Config -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>

        <!-- SpringCloud Alibaba Sentinel -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
        </dependency>

        <!-- SpringBoot Actuator -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <!-- Apache Velocity -->
        <dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity-engine-core</artifactId>
        </dependency>

        <!-- Mysql Connector -->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
        </dependency>

        <!-- RuoYi Common Log -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-common-log</artifactId>
        </dependency>

        <!-- RuoYi Common Swagger -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-common-swagger</artifactId>
        </dependency>

        <!-- 海康sdk接口 -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-api-haikang</artifactId>
        </dependency>

        <!-- okhttp -->
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.12.0</version>
        </dependency>

        <!-- okhttp 调试日志 -->
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>logging-interceptor</artifactId>
            <version>4.12.0</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.google.guava/guava -->
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>33.4.8-jre</version>
        </dependency>

        <!-- zlm 接口 -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-api-zlm</artifactId>
        </dependency>

        <!-- 泉视 接口 -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-api-qs</artifactId>
        </dependency>

        <!-- 海康isup 接口 -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-api-haikang-isup</artifactId>
        </dependency>

        <!-- 大华sdk 接口 -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-api-dahua</artifactId>
        </dependency>

        <!-- gb28181 接口 -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-api-gb28181</artifactId>
        </dependency>

        <!-- jt1078 接口 -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-api-jt1078</artifactId>
        </dependency>

        <!-- onvif 接口 -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-api-onvif</artifactId>
        </dependency>

    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>