<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.ruoyi</groupId>
        <artifactId>ruoyi-modules</artifactId>
        <version>3.6.7</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>ruoyi-modules-qs</artifactId>

    <description>
        ruoyi-modules-qs 泉视模块
    </description>

    <dependencies>

        <!-- SpringCloud Alibaba Nacos -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <!-- SpringCloud Alibaba Nacos Config -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>

        <!-- SpringCloud Alibaba Sentinel -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
        </dependency>

        <!-- SpringBoot Actuator -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <!-- Apache Velocity -->
        <dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity-engine-core</artifactId>
        </dependency>

        <!-- Mysql Connector -->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
        </dependency>

        <!-- RuoYi Common Log -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-common-log</artifactId>
        </dependency>

        <!-- RuoYi Common Swagger -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-common-swagger</artifactId>
        </dependency>

        <!-- 海康sdk接口 -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-api-haikang</artifactId>
        </dependency>

        <!-- 海康isup接口 -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-api-haikang-isup</artifactId>
        </dependency>

        <!-- 泉视接口 -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId> ruoyi-api-qs</artifactId>
        </dependency>

        <!-- 大华sdk接口 -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-api-dahua</artifactId>
        </dependency>

        <!-- onvif接口 -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-api-onvif</artifactId>
        </dependency>

        <!-- jt1078接口 -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-api-jt1078</artifactId>
        </dependency>

        <!-- zlm接口 -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-api-zlm</artifactId>
        </dependency>

        <!-- gb28181接口 -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-api-gb28181</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>33.4.8-jre</version>
        </dependency>

        <!-- 获取系统信息 -->
        <dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
            <version>6.6.5</version>
        </dependency>

        <!--JavaCV相关依赖-->
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv</artifactId>
            <version>1.5.10</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg</artifactId>
            <version>6.1.1-1.5.10</version>
            <classifier>windows-x86_64-gpl</classifier>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg</artifactId>
            <version>6.1.1-1.5.10</version>
            <classifier>linux-x86_64-gpl</classifier>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>