# 基础镜像
FROM eclipse-temurin:17-jre
# author
MAINTAINER ruoyi

# 挂载目录
VOLUME /home/ruoyi
# 创建目录
RUN mkdir -p /home/ruoyi
# 指定路径
WORKDIR /home/ruoyi
# 复制jar文件到路径
COPY ./jar/ruoyi-modules-qs.jar /home/ruoyi/ruoyi-modules-qs.jar
# 启动泉视服务
ENTRYPOINT ["java","-jar","ruoyi-modules-qs.jar"]

